name: Trigger Tests for Forks

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  pr_updater:
    runs-on: ubuntu-latest

    steps:
      - name: main
        uses: didiladi/trigger-workflow-for-pr@main
        with:
          label: run-integration-tests
          dispatch-event: trigger-integration-tests
          token: ${{ secrets.GITHUB_TOKEN }}