name: Run Integration Tests

on:
  pull_request:
    types: [ labeled ]

jobs:
  build:
    if: ${{ github.event.label.name == 'run-integration-tests' }}
    name: Run Integration Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.13
        id: go

      - name: Checkout Fork
        uses: actions/checkout@v2
        with:
          path: fork

      - name: Checkout Upstream
        uses: actions/checkout@v2
        with:
          repository: didiladi/mac-build-test
          path: upstream

      - name: Copy Changes to Upstream Repo
        run: |

          cd fork/
          export BRANCH_NAME_IN_FORK=`git branch --show-current`

          cd ../upstream
          git checkout -b $BRANCH_NAME_IN_FORK

          rm -r !(.*)
          cp -rf ../fork/* .

          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Copy Changes to Upstream Repo"
          git push origin $BRANCH_NAME_IN_FORK

      - name: Check Out Upstream Repo
        uses: actions/checkout@v2
        with:
          repository: didiladi/mac-build-test
          ref: $BRANCH_NAME_IN_FORK

      - name: Build
        run: make build

      - name: Unit Test
        run: make test

      - name: Integration Test
        run: make integration-test
        env:
          ENV_VAR: ${{ secrets.ENV_VAR }}

      - name: Upload Log Files
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: logs
          path: .logs/*.log