name: Run Integration Tests

on:
  pull_request:
    types: [ labeled ]

jobs:
  build:
    if: ${{ github.event.label.name == 'run-integration-tests' }}
    name: Run Integration Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.13
        id: go

      - name: Checkout
        uses: actions/checkout@v2

      - name: Copy Ref to Upstream Repo
        run: |
          echo ${{ github.event.client_payload.ref }}
          echo ${{ github.event.client_payload.sha }}
          git remote add upstream https://github.com/didiladi/mac-build-test.git
          git push upstream HEAD:${{ github.event.client_payload.ref }}

      - name: Check Out Upstream Repo
        uses: actions/checkout@v2
        with:
          repository: https://github.com/didiladi/mac-build-test.git
          ref: ${{ github.event.client_payload.ref }}

      - name: Build
        run: make build

      - name: Unit Test
        run: make test

      - name: Integration Test
        run: make integration-test
        env:
          ENV_VAR: ${{ secrets.ENV_VAR }}

      - name: Upload Log Files
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: logs
          path: .logs/*.log